[platformio]
default_envs = d1_mini
extra_configs =
  optional ota_upload.ini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
monitor_filters = direct
build_flags =
  -std=gnu++17
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson

[env:d1_mini_ota]
extends = env:d1_mini
upload_protocol = espota
upload_port = 192.168.1.100
upload_flags =
  --timeout=60
